-- MySQL Script generated by MySQL Workbench
-- Tue Oct 10 13:36:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema friendship
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema friendship
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `friendship` DEFAULT CHARACTER SET utf8 ;
USE `friendship` ;

-- -----------------------------------------------------
-- Table `friendship`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendship`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `idusers_UNIQUE` (`idusers` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friendship`.`Friendship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendship`.`Friendship` (
  `idFriendship` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idFriendship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friendship`.`friendships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendship`.`friendships` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  INDEX `fk_users_has_users_users1_idx` (`friend_id` ASC),
  INDEX `fk_users_has_users_users_idx` (`users_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_users_has_users_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `friendship`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`friend_id`)
    REFERENCES `friendship`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
