# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-21 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltreview_app', '0006_auto_20171020_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_left', to='loginregis_app.User'),
        ),
    ]
