# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='Authors', to='booksAuthors_app.Book'),
        ),
    ]
