# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LikesBooks_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='Users',
        ),
        migrations.AddField(
            model_name='books',
            name='Uploader',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='Books', to='LikesBooks_app.Users'),
            preserve_default=False,
        ),
    ]
