# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LikesBooks_app', '0002_auto_20171017_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='Uploader',
        ),
        migrations.RemoveField(
            model_name='books',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='books',
            name='Users',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/', verbose_name=id),
            preserve_default=False,
        ),
    ]
