# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LikesBooks_app', '0003_auto_20171017_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='Users',
        ),
        migrations.AddField(
            model_name='books',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_books', to='LikesBooks_app.Users'),
        ),
        migrations.AddField(
            model_name='books',
            name='uploader',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='LikesBooks_app.Users'),
            preserve_default=False,
        ),
    ]
